server:
  port: 9000

spring:
  application:
    name: ai-service

  ai:
    openai:
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      api-key: ${GOOGLE_AI_API_KEY}
      chat:
        options:
          # Model này CÓ trong danh sách JSON của bạn và Miễn phí
          model: gemini-flash-latest

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ai-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.aiservice.event,com.example.aiservice.dto"
        spring.json.type.mapping: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
