server:
  port: 8089

spring:
  application:
    name: delivery-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://delivery-db:5432/delivery_db
#    url: jdbc:postgresql://localhost:5432/delivery_db
    username: postgres
    password: 123456

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    default-models-expand-depth: -1
    doc-expansion: none
    display-request-duration: true
    show-common-extensions: false
    try-it-out-enabled: true
    supported-submit-methods: ["get", "post", "put", "delete", "patch"]
    filter: true
    show-extensions: false
    show-common-extensions: false
    # Hide response examples and schemas
    default-model-expand-depth: -1
    default-model-render-depth: -1
  api-docs:
    path: /v3/api-docs
  show-actuator: false

jwt:
  secret: j4G$z8LpN9vJ^T3Qb7fE2k!wYcB1uL0zRxH5MvAhDpXsCgKj
  expiration: 3600000
  refreshExpiration: 604800000

eureka:
  client:
    service-url:
       defaultZone: http://eureka-server:8761/eureka
#       defaultZone: http://localhost:8761/eureka

